### ISSUE TITLE
Errors in the code

### ISSUE THREAD

**Issue by ykasten** [JiauZhang/DragDiffusion#7]
I cloned the recent code and I see a few errors:
First, when I run the code I get:
  File "DragDiffusion/model.py", line 157, in one_step
    block_feature = self.unet_features(
TypeError: unet_features() got an unexpected keyword argument 'return_dict'

When I remove return_dict=False from line 159 I get:
File "DragDiffusion/model.py", line 185, in unet_features
    default_overall_up_factor = 2**self.num_upsamplers
  File "/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Diffusion' object has no attribute 'num_upsamplers'

Can you please help?

**Comment by JiauZhang** [comment]
diffusers==0.17.1
